#ifndef STR_CONFIG_H
#define STR_CONFIG_H

#define STR_PHOTO           "Photo"
#define STR_WEATHER         "Weather"
#define STR_CALENDAR        "Calendar"
#define STR_ALARM           "Alarm"
#define STR_CLOCK           "Clock"
#define STR_VIDEO           "Video"
#define STR_MUSIC           "Music"
#define STR_SETTING         "Setting"
#define STR_TEMP_C          "℃"
#define STR_TEMP_F          "℉"
#define STR_NO_WEATHER      "Display the weather after networking and positioning"
#define STR_YEAR            "Year"
#define STR_MONTH           "Month"
#define STR_DAY             "Day"
#define STR_TEMP_AM         "AM"
#define STR_TEMP_PM         "PM"
#define STR_MONDAY          "Monday"
#define STR_TUESDAY         "Tuesday"
#define STR_WEDNESDAY       "Wednesday"
#define STR_THURSDAY        "Thursday"
#define STR_FRIDAY          "Friday"
#define STR_SATURDAY        "Saturday"
#define STR_SUNDAY          "Sunday"
#define STR_MON             "Mon"
#define STR_TUE             "Tue"
#define STR_WED             "Wed"
#define STR_THU             "Thu"
#define STR_FRI             "Fri"
#define STR_SAT             "Sat"
#define STR_SUN             "Sun"
#define STR_AM              "Am"
#define STR_PM              "Pm"
#define STR_FLASH_ALL       "ALL"
#define STR_FLASH_INTER     "Internal Storage"
#define STR_FLASH_SD        "SD Card"
#define STR_FLASH_USB       "USB"
#define STR_FLASH_FILE      "Folder"
#define STR_FLASH_FAVOR     "Favorites"
#define STR_TODAY           "Today"
#define STR_HUM             "Humidity"
#define STR_WIN             "Wind"
#define STR_JAN             "January"
#define STR_FEB             "February"
#define STR_MAR             "March"
#define STR_APR             "April"
#define STR_MAY             "May"
#define STR_JUN             "June"
#define STR_JUL             "July"
#define STR_AUG             "August"
#define STR_SEP             "September"
#define STR_OCT             "October"
#define STR_NOV             "November"
#define STR_DEC             "December"
#define STR_EDIT            "Edit"
#define STR_ADD             "Add"
#define STR_CANCEL          "Cancel"
#define STR_OK              "Ok"
#define STR_REPEAT          "Repeat"
#define STR_RINGTONE        "Ringtone"
#define STR_LABEL           "Label"
#define STR_SETTIME         "Set time"
#define STR_DOT             ">"
#define STR_PLATINUM        "Platinum"
#define STR_ARGON       	"Argon"
#define STR_CLASSIC         "Alarm_Classic"
#define STR_HELIUM          "Helium"
#define STR_DELSELFILE      "Delete the selected file?"
#define STR_ROOTTOOUT       "Export files to external storage"
#define STR_IMPORTFILE      "Import the file into memory"
#define STR_CAPTION         "Caption"
#define STR_BGM             "Background Music"
#define STR_INTERVAL        "Slideshow Interval"
#define STR_EFFECT          "Slideshow Transition Effect"
#define STR_PATH  			"Path"
#define STR_SIZE  			"Size"
#define STR_DATE  			"Date"
#define STR_ON              "On"
#define STR_OFF             "Off"
#define STR_5S              "5 seconds"
#define STR_10S             "10 seconds"
#define STR_15S             "15 seconds"
#define STR_30S             "30 seconds"
#define STR_1M              "1 minute"
#define STR_2M              "2 minutes"
#define STR_5M              "5 minutes"
#define STR_10M             "10 minutes"
#define STR_15M             "15 minutes"
#define STR_30M             "30 minutes"
#define STR_NEVER           "Never"
#define STR_NORMAL          "NORMAL"
#define STR_RANDOM          "RANDOM"
#define STR_FADE            "FADE"
#define STR_MOSIAC          "MOSIAC"
#define STR_SLIDE_UP        "SLIDE_UP"
#define STR_SLIDE_DOWN      "SLIDE_DOWN"
#define STR_SLIDE_LEFT      "SLIDE_LEFT"
#define STR_SLIDE_RIGHT     "SLIDE_RIGHT"
#define STR_STRETCH_UP      "STRETCH_UP"
#define STR_STRETCH_DOWN    "STRETCH_DOWN"
#define STR_STRETCH_LEFT    "STRETCH_LEFT"
#define STR_STRETCH_RIGHT   "STRETCH_RIGHT"
#define STR_ZOOM_IN         "ZOOM_IN"
#define ZOOM_OUT            "ZOOM_OUT"
#define STR_PERSIANBLIND_H  "PERSIANBLIND_H"
#define STR_PERSIANBLIND_V  "PERSIANBLIND_V"
#define STR_ALARM_BELL      "Right slide close alarm clock"
#define STR_MYFRAME			"My Frame"
#define STR_ALBUM			"Album Settings"
#define STR_WI_FI			"Wi-Fi"
#define STR_FACTORY			"Factory data reset"
#define STR_HELP			"Help"
#define STR_ABOUT			"About"
#define STR_DEVICEINFO		"Device Info"
#define STR_CONNECTIONCODE	"Connection code:"
#define STR_USERMANAGMENT	"User Management"
#define STR_USERS			"Users"
#define STR_DEVHEAD			"Modify device nickname"
#define STR_EMAILHEAD		"Add friend"
#define STR_VIEWPHOTOS		"View Photos"
#define STR_REMARKNAME      "Remark Name"
#define STR_DELUSER         "Delete User"
#define STR_DELUSERPHOTOS   "Delete User&Photo"
#define STR_BRIGHTNESS      "Brightness"
#define STR_VOLUME          "Volume adjustment"
#define STR_TOUCHSOUNDS     "Touch Sounds"
#define STR_ASSISTIVETOUCH  "Assistive Touch"
#define STR_LANGUAGE        "Language"
#define STR_SLIDESHOW       "Slideshow"
#define STR_SLIDESHOWMODE   "Slideshow Mode"
#define STR_CAPTION         "Caption"
#define STR_DATETIME        "Date And Time"
#define STR_SLEEP           "Sleep"
#define STR_LAU_CN          "简体中文"
#define STR_LAU_EN          "English"
#define STR_LAU_JP          "日本語"
#define STR_LAU_FR          "Français"
#define STR_LAU_GE          "Deutsch"
#define STR_LAU_IT          "Italiano"
#define STR_LAU_PE          "Español"
#define STR_LAU_RU          "Pусский"
#define STR_MONTION         "Montion Sensor"
#define STR_NOTIFICATION    "Notification sound"
#define STR_SEQUENTIAL      "Sequential"
#define STR_RANDOMS         "Random"
#define STR_FACTORYONE      "This will erase all data from your device's internal storage,including:"
#define STR_FACTORYTOW      ".System and app data and settings"
#define STR_FACTORYTHREE    ".Music"
#define STR_FACTORYFOUR     ".Photos"
#define STR_FACTORYFIVE     ".Other user data"
#define STR_FACTORYSIX      "You can select/unselect the following options:"
#define STR_FACTORYSEVEN    "Delete all users and restore the device to inactive"
#define STR_RESETDEVICE     "Reset device"
#define STR_VERSION         "Version"
#define STR_UPDATES         "Check for updates"
#define STR_FRAMEID         "Frame ID"
#define STR_SERIALNUM       "Serial Number"
#define STR_WIFIMAC         "Wi-Fi MAC address"
#define STR_MODEL           "Model"
#define STR_BUILDNUM        "Build Number"
#define STR_INTERNALSTORAGE "Internal Storage"
#define STR_TOTAL           "Total"
#define STR_AVAILABLE       "Available"
#define STR_HELPHEAD1       "Let's download VPHOTO app"
#define STR_HELPSTR1        "Search[VPHOTO]in Google Play/App Store or scan the QR code to download the app."
#define STR_HELPHEAD2       "Let's connect the frame to the app"
#define STR_HELPSTR2        "Scan the QR code or manually enter the connection code to connect the frame to the app."
#define STR_HELPHEAD3       "Share Connection Code"
#define STR_HELPSTR3        "Now you can also invite your families&friends to contribute to your frame,or share the connection code later after completing the initial setting."
#define STR_HELPHEAD4       "Let's start adding photos to the frame"
#define STR_HELPSTR4        "Congratulations!Now you can try to send photos&videos from your phone to the frame or send them later after initial setting."
#define STR_HELPHEAD5       "Add an Mailbox for Sharing"
#define STR_HELPSTR5        "By Pressing[+]in[My Frame],then add mailboxes.By emailing to the mailbox specified in[My Frame],with the subject:bd Connection Code(For Example bd123456789),and 123456789'is an example here,please use the real connection code instead."
#define STR_HELPHEAD6       "Now Send an Email to Share"
#define STR_HELPSTR6        "Check if your email has been added to the user list of the photo frame.If so,send the picture and video as an attachment via email to the designated mailbox,and your photo frame will received it.you can always find this guide in the settings menu."

#endif // STR_CONFIG_H
