#include "app_config_interface.h"
#include "cjson_config.h"

typedef enum {
	CONFIG_PARAM_TYPE_INIT = 0,
	CONFIG_PARAM_TYPE_STRING,
} config_param_type_t;

typedef struct __config_param_tag {
	char				*major;
	char				*minor;
	config_param_type_t type;
	int				val;
	char				*str_config;
} config_param_t;

config_param_t config_param[] = {
	/*PUBLIC_SCENE*/
	{PUBLIC_SCENE, VOLUME, CONFIG_PARAM_TYPE_INIT, DEFAULT_VOLUME, NULL},
	{PUBLIC_SCENE, AUTO_SLEEP, CONFIG_PARAM_TYPE_INIT, DEFAULT_AUTO_SLEEP, NULL},
	{PUBLIC_SCENE, AUTO_CLOSE_SCREEN, CONFIG_PARAM_TYPE_INIT, DEFAULT_CLOSE_SCREEN, NULL},
	{PUBLIC_SCENE, AUTO_POWEROFF, CONFIG_PARAM_TYPE_INIT, DEFAULT_AUTO_POWEROFF, NULL},
	{PUBLIC_SCENE, BACKLIGHT, CONFIG_PARAM_TYPE_INIT, DEFAULT_BACKLIGHT, NULL},
	{PUBLIC_SCENE, ENHANCE_MODE, CONFIG_PARAM_TYPE_INIT, DEFAULT_ENHANCE_MODE, NULL},
	{PUBLIC_SCENE, ENHANCE_BRIGHT, CONFIG_PARAM_TYPE_INIT, DEFAULT_ENHANCE_BRIGHT, NULL},
	{PUBLIC_SCENE, ENHANCE_STATUTION, CONFIG_PARAM_TYPE_INIT, DEFAULT_ENHANCE_STATUTION, NULL},
	{PUBLIC_SCENE, ENHANCE_CONTRAST, CONFIG_PARAM_TYPE_INIT, DEFAULT_ENHANCE_CONTRAST, NULL},
	{PUBLIC_SCENE, LANGUAGE, CONFIG_PARAM_TYPE_INIT, DEFAULT_LANGUAGE, NULL},
	{PUBLIC_SCENE, DATE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_DATE},
	{PUBLIC_SCENE, TIME, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TIME},
	{PUBLIC_SCENE, TIMEZONE, CONFIG_PARAM_TYPE_INIT, DEFAULT_TIMEZONE, NULL},
	{PUBLIC_SCENE, NETTIME, CONFIG_PARAM_TYPE_INIT, DEFAULT_NETTIME, NULL},
	{PUBLIC_SCENE, USERINFO, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_USERINFO},
	{PUBLIC_SCENE, TIMETYPE, CONFIG_PARAM_TYPE_INIT, DEFAULT_TIMETYPE, NULL},
	{PUBLIC_SCENE, CLOCKTYPE, CONFIG_PARAM_TYPE_INIT, DEFAULT_CLOCKTYPE, NULL},
	{PUBLIC_SCENE, VERSION, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_VERSION},
	{PUBLIC_SCENE, MODEL, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_MODEL},
	{PUBLIC_SCENE, BUILDNUM, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_BUILDNUM},
	
	/*MUSIC_SCENE*/
	{MUSIC_SCENE, LOOPMUSIC, CONFIG_PARAM_TYPE_INIT, DEFAULT_LOOPMUSIC, NULL},
	{MUSIC_SCENE, PLAYMODE, CONFIG_PARAM_TYPE_INIT, DEFAULT_PLAYMODE, NULL},
	{MUSIC_SCENE, PATH, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_PATH},
	{MUSIC_SCENE, FILENAME, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_FILENAME},
	{MUSIC_SCENE, FILETYPE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_FILETYPE},
	{MUSIC_SCENE, OFFSET, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_OFFSET},
	{MUSIC_SCENE, INDEX, CONFIG_PARAM_TYPE_INIT, DEFAULT_INDEX, NULL},
	{MUSIC_SCENE, DURATION, CONFIG_PARAM_TYPE_INIT, DEFAULT_DURATION, NULL},

	/*MOVIE_SCENE*/
	{MOVIE_SCENE, LOOP, CONFIG_PARAM_TYPE_INIT, DEFAULT_LOOP, NULL},
	{MOVIE_SCENE, PLAYMODE, CONFIG_PARAM_TYPE_INIT, DEFAULT_PLAYMODE, NULL},
	{MOVIE_SCENE, PATH, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_PATH},
	{MOVIE_SCENE, FILENAME, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_FILENAME},
	{MOVIE_SCENE, FILETYPE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_FILETYPE},
	{MOVIE_SCENE, OFFSET, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_OFFSET},
	{MOVIE_SCENE, INDEX, CONFIG_PARAM_TYPE_INIT, DEFAULT_INDEX, NULL},
	{MOVIE_SCENE, DURATION, CONFIG_PARAM_TYPE_INIT, DEFAULT_DURATION, NULL},

	/*EXT_MUSIC_SCENE*/
	{EXT_MUSIC_SCENE, LOOP, CONFIG_PARAM_TYPE_INIT, DEFAULT_LOOP, NULL},
	{EXT_MUSIC_SCENE, PLAYMODE, CONFIG_PARAM_TYPE_INIT, DEFAULT_PLAYMODE, NULL},
	{EXT_MUSIC_SCENE, PATH, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_PATH},
	{EXT_MUSIC_SCENE, FILENAME, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_FILENAME},
	{EXT_MUSIC_SCENE, FILETYPE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_FILETYPE},
	{EXT_MUSIC_SCENE, OFFSET, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_OFFSET},
	{EXT_MUSIC_SCENE, INDEX, CONFIG_PARAM_TYPE_INIT, DEFAULT_INDEX, NULL},
	{EXT_MUSIC_SCENE, DURATION, CONFIG_PARAM_TYPE_INIT, DEFAULT_DURATION, NULL},

	/*WLAN_SCENE*/
	{WLAN_SCENE, WLAN_MANU_ON, CONFIG_PARAM_TYPE_INIT, DEFAULT_WLAN_MANU_ON, NULL},
	{WLAN_SCENE, WLAN_MANU_CONNECTED, CONFIG_PARAM_TYPE_INIT, DEFAULT_MANU_CONNECTED, NULL},
	{WLAN_SCENE, WLAN_MANU_SSID, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_MANU_SSID},
	{WLAN_SCENE, WLAN_MANU_PASSWORD, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_MANU_PASSWORD},

	/*WEATHER*/
	{WEATHER_SCENE, ANDROIDINFO, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_ANDROIDINFO},
	{WEATHER_SCENE, IOSINFO, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_IOSINFO},
	{WEATHER_SCENE, EMAILLINFO, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_EMAILLINFO},
	{WEATHER_SCENE, DEVNICKNAME, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_DEVNICKNAME},
	{WEATHER_SCENE, IOSLINK, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_IOSLINK},
	{WEATHER_SCENE, GOOGLELINK, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_GOOGLELINK},
	{WEATHER_SCENE, TEMPCORF, CONFIG_PARAM_TYPE_INIT, DEFAULT_TEMPCORF, NULL},
	{WEATHER_SCENE, SERIALADDRESS, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_SERIALADDRESS},
	{WEATHER_SCENE, MACADDRESS, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_MACADDRESS},
	{WEATHER_SCENE, NICKNAME, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_NICKNAME},
	{WEATHER_SCENE, COMPANYNAME, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_COMPANYNAME},
	{WEATHER_SCENE, DEVID, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_DEVID},
	{WEATHER_SCENE, DEVICETOKEN, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_DEVICETOKEN},
	{WEATHER_SCENE, DEVCODE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_DEVCODE},
	{WEATHER_SCENE, EMAILDATA, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_EMAILDATA},
	{WEATHER_SCENE, FCMTOKEN, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_FCMTOKEN},
	{WEATHER_SCENE, CITYNAME, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME},
	{WEATHER_SCENE, CITYID, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID, NULL},
	{WEATHER_SCENE, LATDATA, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA},
	{WEATHER_SCENE, LONDATA, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA},

	/*SETTING*/
	{SETTING_SCENE, TEMPCORF, CONFIG_PARAM_TYPE_INIT, DEFAULT_TEMPCORF, NULL},

	/* 设置界面添加的参数*/
	{SETTING_SCENE, SET_DEV_NAME, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_SET_DEV_NAME},						//设备名
	{SETTING_SCENE, SET_USER_NAME, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_SET_USER_NAME},						//用户名
	{SETTING_SCENE, SET_TP_VOL_MOD, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_TP_VOL_MOD, NULL},					//触摸声音
	{SETTING_SCENE, SET_BOY, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_BOY, NULL},								//悬浮球
	{SETTING_SCENE, SET_AUTOPLAY_MOD, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_AUTOPLAY_MOD, NULL},				//自动播放
	{SETTING_SCENE, SET_PHOTO_DISP_ORDER, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_PHOTO_DISP_ORDER, NULL},		//照片显示顺序
	{SETTING_SCENE, SET_PHOTO_SORT_ORDER, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_PHOTO_SORT_ORDER, NULL},		//排序方式
	{SETTING_SCENE, SET_DESCRIBE, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_DESCRIBE, NULL},						//描述
	{SETTING_SCENE, SET_DATA_STY, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_DATA_STY, NULL},						//自动确定时间
	{SETTING_SCENE, SET_TIME_STY, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_TIME_STY, NULL},						//24小时制
	{SETTING_SCENE, SET_AUTO_STARTUP, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_AUTO_STARTUP, NULL},				//自动开机
	{SETTING_SCENE, SET_BODY_INDUCTION, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_BODY_INDUCTION, NULL},			//人体感应
	{SETTING_SCENE, SET_MSG_VOL, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_MSG_VOL, NULL},						//通知声音
	//{SETTING_SCENE, SET_RES_FACTORY, CONFIG_PARAM_TYPE_INIT, DEFAULT_SET_RES_FACTORY, NULL},

	{WEATHER_SCENE, CITYNAME1, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME1},
	{WEATHER_SCENE, CITYID1, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID1, NULL},
	{WEATHER_SCENE, LATDATA1, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA1},
	{WEATHER_SCENE, LONDATA1, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA1},
	
	{WEATHER_SCENE, CITYNAME2, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME2},
	{WEATHER_SCENE, CITYID2, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID2, NULL},
	{WEATHER_SCENE, LATDATA2, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA2},
	{WEATHER_SCENE, LONDATA2, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA2},
	{WEATHER_SCENE, CITYNAME3, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME3},
	{WEATHER_SCENE, CITYID3, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID3, NULL},
	{WEATHER_SCENE, LATDATA3, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA3},
	{WEATHER_SCENE, LONDATA3, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA3},
	
	{WEATHER_SCENE, CITYNAME4, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME4},
	{WEATHER_SCENE, CITYID4, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID4, NULL},
	{WEATHER_SCENE, LATDATA4, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA4},
	{WEATHER_SCENE, LONDATA4, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA4},
	{WEATHER_SCENE, CITYNAME5, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME5},
	{WEATHER_SCENE, CITYID5, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID5, NULL},
	{WEATHER_SCENE, LATDATA5, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA5},
	{WEATHER_SCENE, LONDATA5, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA5},
	{WEATHER_SCENE, CITYNAME6, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME6},
	{WEATHER_SCENE, CITYID6, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID6, NULL},
	{WEATHER_SCENE, LATDATA6, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA6},
	{WEATHER_SCENE, LONDATA6, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA6},
	{WEATHER_SCENE, CITYNAME7, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME7},
	{WEATHER_SCENE, CITYID7, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID7, NULL},
	{WEATHER_SCENE, LATDATA7, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA7},
	{WEATHER_SCENE, LONDATA7, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA7},
	{WEATHER_SCENE, CITYNAME8, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME8},
	{WEATHER_SCENE, CITYID8, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID8, NULL},
	{WEATHER_SCENE, LATDATA8, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA8},
	{WEATHER_SCENE, LONDATA8, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA8},
	{WEATHER_SCENE, CITYNAME9, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME9},
	{WEATHER_SCENE, CITYID9, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID9, NULL},
	{WEATHER_SCENE, LATDATA9, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA9},
	{WEATHER_SCENE, LONDATA9, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA9},
	{WEATHER_SCENE, CITYNAME10, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_CITYNAME10},
	{WEATHER_SCENE, CITYID10, CONFIG_PARAM_TYPE_INIT, DEFAULT_CITYID10, NULL},
	{WEATHER_SCENE, LATDATA10, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LATDATA10},
	{WEATHER_SCENE, LONDATA10, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_LONDATA10},
	{WEATHER_SCENE, WEEKCUR, CONFIG_PARAM_TYPE_INIT, DEFAULT_WEEKCUR, NULL},
	{WEATHER_SCENE, TEMPCUR, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPCUR},
	{WEATHER_SCENE, TEMPMAXCUR, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPMAXCUR},
	{WEATHER_SCENE, TEMPMINCUR, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPMINCUR},
	{WEATHER_SCENE, HUMCUR, CONFIG_PARAM_TYPE_INIT, DEFAULT_HUMCUR, NULL},
	{WEATHER_SCENE, IDCUR, CONFIG_PARAM_TYPE_INIT, DEFAULT_IDCUR, NULL},
	{WEATHER_SCENE, SPEEDCUR, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_SPEEDCUR},
	{WEATHER_SCENE, WEINFCUR, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_WEINFCUR},
	{WEATHER_SCENE, ICONCUR, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_ICONCUR},
	{WEATHER_SCENE, WEEKONE, CONFIG_PARAM_TYPE_INIT, DEFAULT_WEEKONE, NULL},
	{WEATHER_SCENE, TEMPONE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPONE},
	{WEATHER_SCENE, TEMPMAXONE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPMAXONE},
	{WEATHER_SCENE, TEMPMINONE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPMINONE},
	{WEATHER_SCENE, HUMONE, CONFIG_PARAM_TYPE_INIT, DEFAULT_HUMONE, NULL},
	{WEATHER_SCENE, IDONE, CONFIG_PARAM_TYPE_INIT, DEFAULT_IDONE, NULL},
	{WEATHER_SCENE, SPEEDONE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_SPEEDONE},
	{WEATHER_SCENE, WEINFONE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_WEINFONE},
	{WEATHER_SCENE, ICONONE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_ICONONE},
	{WEATHER_SCENE, WEEKTOW, CONFIG_PARAM_TYPE_INIT, DEFAULT_WEEKTOW, NULL},
	{WEATHER_SCENE, TEMPTOW, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPTOW},
	{WEATHER_SCENE, TEMPMAXTOW, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPMAXTOW},
	{WEATHER_SCENE, TEMPMINTOW, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPMINTOW},
	{WEATHER_SCENE, HUMTOW, CONFIG_PARAM_TYPE_INIT, DEFAULT_HUMTOW, NULL},
	{WEATHER_SCENE, IDTOW, CONFIG_PARAM_TYPE_INIT, DEFAULT_IDTOW, NULL},
	{WEATHER_SCENE, SPEEDTOW, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_SPEEDTOW},
	{WEATHER_SCENE, WEINFTOW, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_WEINFTOW},
	{WEATHER_SCENE, ICONTOW, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_ICONTOW},
	{WEATHER_SCENE, WEEKTHREE, CONFIG_PARAM_TYPE_INIT, DEFAULT_WEEKTHREE, NULL},
	{WEATHER_SCENE, TEMPTHREE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPTHREE},
	{WEATHER_SCENE, TEMPMAXTHREE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPMAXTHREE},
	{WEATHER_SCENE, TEMPMINTHREE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_TEMPMINTHREE},
	{WEATHER_SCENE, HUMTHREE, CONFIG_PARAM_TYPE_INIT, DEFAULT_HUMTHREE, NULL},
	{WEATHER_SCENE, IDTHREE, CONFIG_PARAM_TYPE_INIT, DEFAULT_IDTHREE, NULL},
	{WEATHER_SCENE, SPEEDTHREE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_SPEEDTHREE},
	{WEATHER_SCENE, WEINFTHREE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_WEINFTHREE},
	{WEATHER_SCENE, ICONTHREE, CONFIG_PARAM_TYPE_STRING, 0, DEFAULT_ICONTHREE},

	/*PHOTO*/
	{PHOTO_SCENE, SET_MSG_BGM, CONFIG_PARAM_TYPE_INIT, MSG_BGM, NULL},
	{PHOTO_SCENE, SET_MSG_INTERVAL, CONFIG_PARAM_TYPE_INIT, MSG_INTERVAL, NULL},
	{PHOTO_SCENE, SET_MSG_EFFECT, CONFIG_PARAM_TYPE_INIT, MSG_EFFECT, NULL},
};

static cjson_config_t va_save_param;
static cjson_config_t va_userinfo_param;
static cjson_config_t va_filedown_param;
#ifdef _UCHIP_T113
void va_save_param_init(void)
{
	memset(&va_save_param, 0x00, sizeof(va_save_param));
	va_save_param.config_path = VA_SAVE_PATH;
	init_cjson_config(&va_save_param);
}

void va_save_param_uninit(void)
{
	uninit_cjson_config(&va_save_param);
}

int read_int_type_param(char *major, char *minor, int *param)
{
	int ret = 0;
	if (strlen(major) == 0 || strlen(minor)==0) {
		com_warn("\n");
		ret = -1;
		goto END;
	}
	*param = 0;

	ret = read_int_type_cjson_config(&va_save_param, major, minor, param);
END:
	return ret;
}

int write_int_type_param(char *major, char *minor, int param)
{
	int ret;
	if (strlen(major) == 0 || strlen(minor)==0) {
		com_warn("\n");
		ret = -1;
		goto END;
	}
	ret = write_int_type_cjson_config(&va_save_param, major, minor, param);
END:
	return ret;
}

int read_string_type_param(char *major, char *minor, char *str, int len)
{
	int ret;
	if(strlen(major)==0 || strlen(minor)==0 || len<=0) {
		com_warn("\n");
		ret = -1;
		goto END;
	}

	ret = read_string_type_cjson_config(&va_save_param,  major, minor, str, len);
END:
	return ret;
}

int write_string_type_param(char *major, char *minor, char *str, int len)
{
	int ret;
	if(strlen(major)==0 || strlen(minor)==0 || len<=0) {
		com_warn("major:%s, minor:%s\n", major, minor);
		ret = -1;
		goto END;
	}
	ret = write_string_type_cjson_config(&va_save_param, major, minor, str, len);
END:
	return ret;
}

void va_userinfo_param_init(void)
{
	memset(&va_userinfo_param, 0x00, sizeof(va_userinfo_param));
	va_userinfo_param.config_path = VA_USER_PATH;
	init_cjson_config(&va_userinfo_param);
}

int read_string_userinfo_param(char *major, char *minor, char *str, int len)
{
	int ret;
	if(strlen(major)==0 || strlen(minor)==0 || len<=0) {
		com_warn("\n");
		ret = -1;
		goto END;
	}

	ret = read_string_type_cjson_config(&va_userinfo_param,  major, minor, str, len);
END:
	return ret;
}

int write_string_userinfo_param(char *major, char *minor, char *str, int len)
{
	int ret;
	if(strlen(major)==0 || strlen(minor)==0 || len<=0) {
		com_warn("major:%s, minor:%s\n", major, minor);
		ret = -1;
		goto END;
	}
	ret = write_string_type_cjson_config(&va_userinfo_param, major, minor, str, len);
END:
	return ret;
}

int clean_string_userinfo_param(char *major)
{
	int ret;
	if(strlen(major)==0) {
		com_warn("major:%s\n", major);
		ret = -1;
		goto END;
	}
	ret = clean_string_type_cjson_config(&va_userinfo_param, major);
END:
	return ret;
}

int clean_string_all_userinfo_param(void)
{
	int ret;
	ret = clean_string_type_cjson_all_config(&va_userinfo_param);
END:
	return ret;
}

void va_downfile_data_param_init(void)
{
	memset(&va_filedown_param, 0x00, sizeof(va_filedown_param));
	va_filedown_param.config_path = VA_DOWNFILE_INFO;
	init_cjson_config(&va_filedown_param);
}

int read_string_downfile_data_param(char *major, char *str1, int len1, char *str2, int len2, char *str3, int len3)
{
	int ret;
	if(strlen(major)==0 || len1<=0 || len2<=0 || len3<=0) {
		com_warn("major:%s, minor1:%s minor2:%s\n", major, DOWNFILE_PATCH, DOWNFILE_URL);
		ret = -1;
		goto END;
	}
	ret = read_string_cjson_config(&va_filedown_param, major, USER_ID, str1, len1,DOWNFILE_PATCH, str2, len2,DOWNFILE_URL, str3, len3);
END:
	return ret;
}

int write_string_downfile_data_param(char *major, char *str1, int len1, char *str2, int len2, char *str3, int len3)
{
	int ret;
	if(strlen(major)==0 || len1<=0 || len2<=0 || len3<=0) {
		com_warn("major:%s, minor1:%s minor2:%s\n", major, DOWNFILE_PATCH, DOWNFILE_URL);
		ret = -1;
		goto END;
	}
	ret = write_string_cjson_config(&va_filedown_param, major, USER_ID, str1, DOWNFILE_PATCH, str2, DOWNFILE_URL, str3);
END:
	return ret;
}
int check_string_downfile_data_param(char *major)
{
	int ret;
	if(strlen(major)==0 ) {
		com_warn("major:%s\n", major);
		ret = -1;
		goto END;
	}
	ret = check_string_cjson_config(&va_filedown_param, major);
END:
	return ret;
}
int clean_string_downfile_data_param(char *major)
{
	int ret;
	if(strlen(major)==0) {
		com_warn("major:%s\n", major);
		ret = -1;
		goto END;
	}
	ret = clean_string_cjson_config(&va_filedown_param, major);
END:
	return ret;
}

int clean_string_all_downfile_data_param(void)
{
	int ret;
	ret = clean_string_cjson_all_config(&va_filedown_param);
END:
	return ret;
}
void app_config_param_init(int reset)
{
	int index = 0;

	if (!reset) {
		va_save_param_init();
	}

	if (reset || access(VA_SAVE_PATH, F_OK) != 0) {
		for (index = 0; index < sizeof(config_param)/sizeof(config_param[0]); index++) {
			if (config_param[index].type == CONFIG_PARAM_TYPE_INIT) {
				write_int_type_param(config_param[index].major, config_param[index].minor, config_param[index].val);
			} else if (config_param[index].type == CONFIG_PARAM_TYPE_STRING) {
				int len = 0;
				if (config_param[index].str_config != NULL) {
					len = strlen(config_param[index].str_config);
				}
				write_string_type_param(config_param[index].major, config_param[index].minor, config_param[index].str_config, len);
			}
		}
	}
	va_userinfo_param_init();
	va_downfile_data_param_init();
}
#endif
